export const defaultStack = [
    "JAVA",
    "Android",
    "iOS",
    "Python",
    "JSP",
    "PHP",
    "ASP",
    "C",
    "C#",
    "C++",
    "MFC",
    ".Net",
    "Node.js",
    "Vue.js",
    "React.js",
    "JQuery",
    "Javascript",
    "Oracle",
    "MMSQL",
    "MySQL",
    "MariaDB",
    "MongoDB",
    "PostgreSQL",
    "HTML5",
    "CSS",
    "BootStrap",
    "Typescript",
    "Photoshop",
    "Illustrator",
    "Adobe XD",
    "InDesign",
    "Zeplin",
    "Sketch",
    "Spring Boot",
];

export const defaultPosition = ["Front", "Back", "UI/UX", "디자이너"];

export const user = {
    profilePicture:
        "https://dszw1qtcnsa5e.cloudfront.net/community/20220519/453159ca-e328-429c-9b3f-460fc592d963/%EA%B7%80%EC%97%AC%EC%9A%B4%EB%AA%B0%EB%9D%BC%EB%AA%A8%EC%BD%94%EC%BD%94.png",
    nickname: "모코코",
    githubId: "Mococo",
    introduction: "update",
    listEnroll: true,
    position: ["FE", "BE"],
    stack: ["Javascript", "Typescript", "React.js", "Node.js", "Next.js", "BootStrap", "tailwindcss"],
    projectList: [
        {
            boardId: 1,
            title: "title",
            startDate: "1/1",
            deadline: "1/5",
            createdAt: "2023-09-04T13:21:41.883149",
            modifiedAt: null,
            recruitNum: 5,
            recruitStatus: false,
            viewCount: 0,
        },
        {
            boardId: 2,
            title: "title",
            startDate: "1/1",
            deadline: "1/5",
            createdAt: "2023-09-04T13:21:41.883149",
            modifiedAt: null,
            recruitNum: 5,
            recruitStatus: false,
            viewCount: 0,
        },
    ],
    studyList: [
        {
            studyId: 1,
            title: "title",
            startDate: "1/1",
            deadline: "1/5",
            createdAt: "2023-09-04T13:21:41.883149",
            modifiedAt: null,
            recruitNum: 5,
            recruitStatus: false,
            viewCount: 0,
        },
    ],
    infoBoardList: [],
    blockMemberList: ["test2"],
    modifiedAt: "2023-09-04T11:20:03.373275",
    oauthUser: false,
};
