export const defaultStack = [
    "JAVA",
    "Android",
    "iOS",
    "Python",
    "JSP",
    "PHP",
    "ASP",
    "C",
    "C#",
    "C++",
    "MFC",
    ".Net",
    "Node.js",
    "Vue.js",
    "React.js",
    "JQuery",
    "Javascript",
    "Oracle",
    "MMSQL",
    "MySQL",
    "MariaDB",
    "MongoDB",
    "PostgreSQL",
    "HTML5",
    "CSS",
    "BootStrap",
    "Typescript",
    "Photoshop",
    "Illustrator",
    "Adobe XD",
    "InDesign",
    "Zeplin",
    "Sketch",
    "Spring Boot",
];

export const defaultPosition = ["Front", "Back", "UI/UX", "디자이너"];
