name: Java CI with Gradle

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x server/DevSquad/gradlew

      - name: Build with Gradle
        working-directory: server/DevSquad
        run: ./gradlew clean build

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t devsquad -f server/DevSquad/Dockerfile .
          docker tag devsquad ehdals0405/devsquad:${GITHUB_SHA::7}
          docker push ehdals0405/devsquad:${GITHUB_SHA::7}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ehdalsKey.pem
          chmod 600 ehdalsKey.pem
      - name: Deploy to Server
        run: |
          ssh -i "ehdalsKey.pem" ec2-user@ec2-43-202-24-155.ap-northeast-2.compute.amazonaws.com "bash && cd ~" <<EOF
            if sudo docker ps -a --format \\'{{.Names}}\\' | grep -q \'^server$\\'; then
              sudo docker stop server
              sudo docker rm server
            fi 
            sudo docker pull ehdals0405/devsquad:${GITHUB_SHA::7}
            sudo docker tag ehdals0405/devsquad:${GITHUB_SHA::7} devsquad
            sudo docker run -d --name server --env-file env_file -p 8080:8080 devsquad
          EOF

